### ISSUE TITLE
Marine Software Quality Push

### ISSUE THREAD

**Issue by VeckoTheGecko** [OceanParcels/virtualship#64]
Hello! Met with @ammedd today to discuss what improvements can be made to the codebase to support and mature this project. My involvement in this project is part of a larger UU-NIOZ collaboration project aiming to improve software quality to support open science.

The items I'll be working on for now are:

- [x] Merge `develop` into `main` and delete develop branch
- [x] Contributing guidelines and code of conduct
- [x] Create a documentation website (with ReadTheDocs)
- [x] Releases
  - Get conda release up and running
  - Get PyPI release up and running
- [x] Update the README
- [x] Formalise code quality tooling via pre-commit
- [x] Use nox for workflow running
  - Pytest
  - Docs generation
- [x] Investigate installation method (i.e., migrating completely to using conda)
- [x] Coverage support
- [x] Admin
    - Add @ammedd to PyPI, Conda, Codecov, and ReadTheDocs

Thanks for your involvement so far @surgura , its been a pleasure reading your code :)

**Comment by surgura** [comment]
I recommend dropping support for older python versions only if they pose an actual problem during development. Previous educational software experience showed that many students use old laptops with ancient python versions. Save yourself time and make it work if you can :)

**Comment by VeckoTheGecko** [comment]
Hmm. I don't think it depends how we promote installation to students.

If they install via conda then its fine (since Python is installed as part of the environment), if its via pip then it can pose an issue. I think promoting a 100% Conda installation would be good if our dependencies allow it and would be good educationally (as scientific Python ecosystem is very Conda focussed).

Regardless, the latest Parcels has dropped support for Python 3.8 and 3.9 so I think it's necessary to update. I'll expand the CI coverage to also include our minimum supported Python version

**Comment by surgura** [comment]
Also, it's up to you if you want to delete the develop branch, but I had it there so we can make 100% sure that main always matches a version tag. That way we are sure if people are stupid and pull main that at least they have a proper release that works. Development can sometimes be broken which you only figure out after a few merges

**Comment by surgura** [comment]
Regarding conda, I recommend to keep it pip installable as well. The only problem is that there is no C++ compiler packages for Parcels. However, there are plenty of people that know what they are doing regarding installing a compiler and removing pyproject.toml and forcing them to use conda is a really big pain. Conda may be the standard in this research group, but there is a big community that avoids conda like the plague

**Comment by VeckoTheGecko** [comment]
> I had it there so we can make 100% sure that main always matches a version tag

I see. I'm familiar with the concept of [Git Flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) but I've never worked in a codebase that uses it before. I was thinking it could become difficult once documentation is introduced as it then becomes a question of which branch to point to docs to. I think it would be good to revisit the branching strategy once we know how users are going to be exposed to the project (are they going to clone the repo? do they create an environment using Conda?), and what the documentation looks like. A trunk branching strategy is a bit easier on my brain for the moment though :) .


> Conda may be the standard in this research group, but there is a big community that avoids conda like the plague

Good to know! I didn't know there was a community that avoids conda, I thought it was ubiquitous. I think perhaps both pip and conda would be the way to go then. The conda way would still have the `pyproject.toml` file for metadata, but using `meta.yml` for dependencies.

**Comment by ammedd** [comment]
I think the associated PR will also close #59

**Comment by VeckoTheGecko** [comment]
I'd say this is done now
